## < All Credits Goes To DarkBoy For Making This Bot > ##
## Main bot Config ##
mainprefix: '$' # Main Prefix 
token: 'NzM4ODczNzE0MzMzOTc0NjUw.XySPxQ.sRYEnJr1tbxfknc7-8Kybyh_g1g' # Token of your bot
status: 'testing rn' # ur bot status
## Join Support Guild:   ##
